name: UrMinion

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python.exe -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install xvfb
        run: |
          sudo apt-get install -y xvfb
          xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' mainpy.py

      - name: Run tests with pytest
        run: |
          export DISPLAY=:99
          Xvfb :99 &
          pytest --disable-warnings
          
