name: UrMinion

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb  # Install Xvfb for virtual display
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-mock  # Install pytest and mock library

      - name: Run Xvfb
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x16 &  # Start Xvfb virtual display

      - name: Test with pytest
        run: |
          python -m pytest tests/
